:cs add /home/phoenix/opt/project/linux/drivers/cscope.out /home/phoenix/opt/project/linux/drivers
:cs add /home/phoenix/opt/project/linux/include/cscope.out /home/phoenix/opt/project/linux/include
:cs add /home/phoenix/opt/project/linux/lib/cscope.out /home/phoenix/opt/project/linux/lib
:cs add /home/phoenix/opt/project/linux/mm/cscope.out /home/phoenix/opt/project/linux/mm
:cs add /home/phoenix/opt/project/linux/security/cscope.out /home/phoenix/opt/project/linux/security
:cs add /home/phoenix/opt/project/linux/usr/cscope.out /home/phoenix/opt/project/linux/usr
:cs add /home/phoenix/opt/project/linux/block/cscope.out /home/phoenix/opt/project/linux/block
:cs add /home/phoenix/opt/project/linux/crypto/cscope.out /home/phoenix/opt/project/linux/crypto
:cs add /home/phoenix/opt/project/linux/firmware/cscope.out /home/phoenix/opt/project/linux/firmware
:cs add /home/phoenix/opt/project/linux/init/cscope.out /home/phoenix/opt/project/linux/init
:cs add /home/phoenix/opt/project/linux/net/cscope.out /home/phoenix/opt/project/linux/net
:cs add /home/phoenix/opt/project/linux/samples/cscope.out /home/phoenix/opt/project/linux/samples
:cs add /home/phoenix/opt/project/linux/virt/cscope.out /home/phoenix/opt/project/linux/virt
:cs add /home/phoenix/opt/project/linux/fs/cscope.out /home/phoenix/opt/project/linux/fs
:cs add /home/phoenix/opt/project/linux/ipc/cscope.out /home/phoenix/opt/project/linux/ipc
:cs add /home/phoenix/opt/project/linux/kernel/cscope.out /home/phoenix/opt/project/linux/kernel
:cs add /home/phoenix/opt/project/linux/scripts/cscope.out /home/phoenix/opt/project/linux/scripts
:cs add /home/phoenix/opt/project/linux/tools/cscope.out /home/phoenix/opt/project/linux/tools
:cs add /home/phoenix/opt/project/linux/arch/powerpc/cscope.out /home/phoenix/opt/project/linux/arch/powerpc
:cs add /home/phoenix/opt/project/linux/arch/mips/cscope.out /home/phoenix/opt/project/linux/arch/mips
:cs add /home/phoenix/opt/project/linux/arch/x86/cscope.out /home/phoenix/opt/project/linux/arch/x86
:cs add /home/phoenix/opt/project/linux/sound/cscope.out /home/phoenix/opt/project/linux/sound
